---
- name: Доставляем и запускаем docker-compose на сервере
  hosts: banking_server
  become: true
  gather_facts: false
  vars:
    deploy_dir: /opt/banking/compose

  tasks:
    - name: Создаем дирректорию для docker-compose
      file:
        path: "{{ deploy_dir }}"
        state: directory
        mode: "0755"

    - name: Копируем docker-compose file
      copy:
        src: "{{ playbook_dir }}/../../docker-compose/docker-compose.yml"
        dest: "{{ deploy_dir }}/docker-compose.yml"
        mode: "0644"

    - name: Копируем .env file
      copy:
        src: "{{ playbook_dir }}/../vault/docker-compose.env"
        dest: "{{ deploy_dir }}/.env"
        mode: "0600"

    - name: Запускаем docker-compose
      command: docker compose up -d
      args:
        chdir: "{{ deploy_dir }}"
